/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
public class WelcomePage extends javax.swing.JFrame {
     String uname = null;
    /**
     * Creates new form WelcomePage
     */
    public WelcomePage() {
        initComponents();
       
    }
    public WelcomePage(String name) {
        initComponents();
       
       
        jLabel2.setText(uname);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jAddLoanButton2 = new javax.swing.JButton();
        jAddMemberButton1 = new javax.swing.JButton();
        jAddBookButton1 = new javax.swing.JButton();
        jReturnBookButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Welcome to Kevin Street Library");

        jLabel2.setText("jLabel2");

        jAddLoanButton2.setText("Add Loan");
        jAddLoanButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAddLoanButton2ActionPerformed(evt);
            }
        });

        jAddMemberButton1.setText("Add Member");
        jAddMemberButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAddMemberButton1ActionPerformed(evt);
            }
        });

        jAddBookButton1.setText("Add New Book");
        jAddBookButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAddBookButton1ActionPerformed(evt);
            }
        });

        jReturnBookButton1.setText("Return Book");
        jReturnBookButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jReturnBookButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jAddLoanButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jAddMemberButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jAddBookButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jReturnBookButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jAddLoanButton2)
                    .addComponent(jAddMemberButton1)
                    .addComponent(jAddBookButton1)
                    .addComponent(jReturnBookButton1))
                .addContainerGap(166, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(416, 338));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jAddLoanButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAddLoanButton2ActionPerformed
        // Add Loan Button handling code:
        AddBookLoan Loan = new AddBookLoan(null);
        Loan.setVisible(true);
        setVisible(false); 
    }//GEN-LAST:event_jAddLoanButton2ActionPerformed

    private void jAddMemberButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAddMemberButton1ActionPerformed
        // Add member handling code here:
        AddMember Mem = new AddMember(null);
        Mem.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jAddMemberButton1ActionPerformed

    private void jAddBookButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAddBookButton1ActionPerformed
        // Add new book handling code here:
        AddNewBook book = new AddNewBook(null);
        book.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jAddBookButton1ActionPerformed

    private void jReturnBookButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jReturnBookButton1ActionPerformed
        // TODO add your handling code here:
        ReturnBook book = new ReturnBook(null);
        book.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jReturnBookButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WelcomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WelcomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WelcomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WelcomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WelcomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAddBookButton1;
    private javax.swing.JButton jAddLoanButton2;
    private javax.swing.JButton jAddMemberButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton jReturnBookButton1;
    // End of variables declaration//GEN-END:variables
}
